# Generated by Django 2.1.3 on 2018-12-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('friendname', models.CharField(max_length=20)),
                ('is_receive', models.BooleanField(default=True)),
                ('is_showplan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户好友信息',
                'verbose_name_plural': '用户好友信息',
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='MemoryDayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('anniversary_date', models.DateField()),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(default='')),
                ('is_remind', models.BooleanField(default=False)),
                ('remind_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '纪念日数据',
                'verbose_name_plural': '纪念日数据',
                'db_table': 'memoryday',
            },
        ),
        migrations.CreateModel(
            name='MessagesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('messagefrom', models.CharField(max_length=20)),
                ('messagecontent', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_added', models.BooleanField(default=False)),
                ('receive_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '用户接受消息',
                'verbose_name_plural': '用户接受消息',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='PlanCommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('comment_from', models.CharField(max_length=20)),
                ('comment_to', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('comment_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '日程评论数据',
                'verbose_name_plural': '日程评论数据',
                'db_table': 'plancomment',
            },
        ),
        migrations.CreateModel(
            name='PlanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(default='')),
                ('priority', models.SmallIntegerField(choices=[(0, '很重要很紧急'), (1, '很重要不紧急'), (2, '不重要很紧急'), (3, '不重要不紧急')], default=3)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('during', models.PositiveIntegerField(blank=True, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, null=True)),
                ('plantype', models.PositiveSmallIntegerField(choices=[(0, '日计划'), (1, '周计划'), (2, '月计划'), (3, '自定义计划')], default=0)),
                ('color', models.SmallIntegerField(default=0)),
                ('is_show_to_friends', models.BooleanField(default=False)),
                ('is_remind', models.BooleanField(default=False)),
                ('is_complicated', models.BooleanField(default=False)),
                ('comp_datetime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(default='')),
            ],
            options={
                'verbose_name': '日程信息',
                'verbose_name_plural': '日程信息',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanRemindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_remind', models.BooleanField(default=False)),
                ('remind_datetime', models.DateTimeField()),
                ('remind_from', models.CharField(max_length=20)),
                ('which_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.PlanInfo')),
            ],
            options={
                'verbose_name': '日程提醒数据',
                'verbose_name_plural': '日程提醒数据',
                'db_table': 'planremind',
            },
        ),
        migrations.CreateModel(
            name='StatisticsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('planamount', models.PositiveIntegerField()),
                ('compamount', models.PositiveIntegerField()),
                ('message_amount', models.PositiveIntegerField()),
                ('friends_amount', models.PositiveIntegerField()),
                ('friends_plan_amount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '用户数据',
                'verbose_name_plural': '用户数据',
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('theme_color', models.SmallIntegerField(default=0)),
                ('is_show', models.BooleanField(default=True)),
                ('is_receive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='statisticsinfo',
            name='which_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.UserInfo'),
        ),
        migrations.AddField(
            model_name='planinfo',
            name='which_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.UserInfo'),
        ),
        migrations.AddField(
            model_name='plancommentinfo',
            name='which_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.PlanInfo'),
        ),
        migrations.AddField(
            model_name='memorydayinfo',
            name='which_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.UserInfo'),
        ),
        migrations.AddField(
            model_name='friendsinfo',
            name='which_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.UserInfo'),
        ),
    ]
