# Generated by Django 2.1.3 on 2018-12-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daytraceuser', '0002_memorydayinfo_during'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesinfo',
            name='which_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daytraceuser.UserInfo'),
        ),
        migrations.AlterField(
            model_name='messagesinfo',
            name='receive_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
